# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OWkeQdqmBoCRjQTsDIRcwgzRR7Itw7e9
"""

import streamlit as st
import pandas as pd
import numpy as np
n = st.slider("n", 5, 100, step=1)
chart_data = pd.DataFrame(np.random.randn(n),columns=['data'])
st.line_chart(chart_data)

